### ISSUE TITLE
Featured images on Twenty Nineteen homepage appear stretched

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#1747]
Unlike #1656 where the image is not filling the entire width of the content, featured images in the post list of the homepage are stretching too wide on larger monitors:

![image](https://user-images.githubusercontent.com/134745/50035327-61846f00-ffb6-11e8-8128-86ddb2fbad33.png)

**Comment by westonruter** [comment]
This may need the same fix as done for Twenty Seventeen (#1677). /cc @kienstra

**Comment by westonruter** [comment]
I believe the fix for this has been identified in #1939 (https://github.com/ampproject/amp-wp/pull/1939/commits/3ac927035c007b586fe680c2bd40d27fd7be7f0f) namely:

```css
.wp-block-image:not(#_) > figure > amp-img {
	display: inline-block;
	vertical-align: middle;
}
```
