### ISSUE TITLE
Center-aligned animated GIF appears stretched

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2792]
Given `post_content`:

```html
Paragraph before image.

<img class="aligncenter size-full wp-image-2037" src="https://blog.amp.dev/wp-content/uploads/2018/05/webpackaging.gif" alt="webpackaging" width="394" height="786">

Paragraph after image
```

This will be shown in the editor as a Classic block. On the frontend, it will be rendered in AMP as stretched:

> ![image](https://user-images.githubusercontent.com/134745/60994322-2b695c80-a305-11e9-8dc5-60b98ff3fce6.png)

I tried converting it to blocks:

```html
<!-- wp:paragraph -->
<p>Paragraph before image.</p>
<!-- /wp:paragraph -->

<!-- wp:image {"align":"center","id":2037} -->
<div class="wp-block-image"><figure class="aligncenter"><img src="https://blog.amp.dev/wp-content/uploads/2018/05/webpackaging.gif" alt="webpackaging" class="wp-image-2037"/></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>Paragraph after image</p>
<!-- /wp:paragraph -->
```

This fixed [the issue on blog.amp.dev](https://blog.amp.dev/2018/05/08/a-first-look-at-using-web-packaging-to-improve-amp-urls/), but for some reason it did not fix the issue for me locally in Twenty Nineteen.

The issue appears to be with this default CSS in the plugin:

https://github.com/ampproject/amp-wp/blob/2fe67959eb425b83273699c885881c85de1eb96b/assets/css/amp-default.css#L7-L10

This is unexpectedly getting converted by `\AMP_Style_Sanitizer::ampify_ruleset_selectors` into:

```css
amp-img.amp-wp-enforced-sizes[layout="intrinsic"] > img, 
amp-anim.amp-wp-enforced-sizes[layout="intrinsic"] > amp-img, 
amp-anim.amp-wp-enforced-sizes[layout="intrinsic"] > amp-anim, 
.amp-wp-unknown-size > amp-img, 
.amp-wp-unknown-size > amp-anim {
    object-fit: contain
}
```

Clearly this is wrong. The `> img` should be left untouched.

Note that this is particularly a problem for `amp-anim`. The `amp-img` is fine, which is why we didn't notice this before.
