### ISSUE TITLE
Image circle mask not working

### ISSUE THREAD

**Issue by barklund** [ampproject/amp-wp#3503]
## Bug Description

If you select block style "Circle mask" for your image, no Image shows up in the actual story.

## Expected Behaviour

Image with circle mask should show up in story.

## Steps to reproduce

1. Create new story.
2. Add image block and select any image.
3. Use block style dropdown in top bar and select "circle mask".
4. Preview story.
5. See that the image is missing.

## Screenshots

<img width="577" alt="Screenshot 2019-10-14 at 18 04 08" src="https://user-images.githubusercontent.com/637548/66786402-30aee800-eeae-11e9-8989-08d9dcf9f9ad.png">

## Additional context

 - WordPress version:
 - Plugin version: **develop**
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
Oh, looks like this is not only an issue for stories, but a general issue in the plugin.

Gutenberg uses CSS as follows for the mask:

```css
.is-style-circle-mask img {
    -webkit-mask-image: url(data:image/svg+xml;utf8,<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"/></svg>);
    mask-image: url(data:image/svg+xml;utf8,<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"/></svg>);
    mask-mode: alpha;
    -webkit-mask-repeat: no-repeat;
    mask-repeat: no-repeat;
    -webkit-mask-size: contain;
    mask-size: contain;
    -webkit-mask-position: center;
    mask-position: center;
    border-radius: none;
}
```

([source](https://github.com/WordPress/gutenberg/blob/ed5ec9a1e521cca17eb36029b95603252a55a282/packages/block-library/src/image/style.scss#L60-L77))

The AMP plugin turns this into:

```css
.is-style-circle-mask amp-img {
    -webkit-mask-image: url(data:image/svg+xml;utf8,<svgviewBox=\"00100100\"xmlns=\"http://www.w3.org/2000/svg\"><circlecx=\"50\"cy=\"50\"r=\"50\"/></svg>);
    mask-image: url(data:image/svg+xml;utf8,<svgviewBox=\"00100100\"xmlns=\"http://www.w3.org/2000/svg\"><circlecx=\"50\"cy=\"50\"r=\"50\"/></svg>);
    mask-mode: alpha;
    -webkit-mask-repeat: no-repeat;
    mask-repeat: no-repeat;
    -webkit-mask-size: contain;
    mask-size: contain;
    -webkit-mask-position: center;
    mask-position: center;
    border-radius: none;
}
```

**Comment by swissspidy** [comment]
This feature was [introduced in Gutenberg 6.4](https://github.com/WordPress/gutenberg/pull/16475), so it will probably be used more when WordPress 5.3 is released. Which means it would be nice if it could be addressed in time.

@westonruter Thoughts?

**Comment by westonruter** [comment]
Thanks for pointing this out. This is something that @felixarntz also noticed in #2542 in relation to Site Kit. I think Gutenberg actually may be at fault here. While browsers appear to recognize this syntax, it appears to be actually invalid when I check in the [CSS validator](https://jigsaw.w3.org/css-validator/):

![image](https://user-images.githubusercontent.com/134745/67037078-ae9f0900-f0d1-11e9-9305-985117911957.png)

I think Gutenberg actually needs to put this `data:` URL in quotes, or else base64-encode it.

So the question is this: can Gutenberg be patched to fix this for 5.3 or is it something we need to account for ourselves now?

**Comment by swissspidy** [comment]
Hmm the CSS I pasted above is actually the source SCSS, the generated one from `wp-block-library.css` does have quotes and looks like this:

```css
.is-style-circle-mask img{
	-webkit-mask-image:url('data:image/svg+xml;utf8,<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"/></svg>');
	mask-image:url('data:image/svg+xml;utf8,<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"/></svg>');
	mask-mode:alpha;
	-webkit-mask-repeat:no-repeat;
	mask-repeat:no-repeat;
	-webkit-mask-size:contain;
	mask-size:contain;
	-webkit-mask-position:center;
	mask-position:center;
	border-radius:none
}
```

The CSS validator doesn't complain about the URL:

![Screenshot 2019-10-18 at 10 49 24](https://user-images.githubusercontent.com/841956/67080222-08b4d280-f195-11e9-873a-7dcddafb3d85.png)

So I am not sure what's there to patch in Gutenberg. But it would probably be too late for 5.3 anyway as it would be a pretty minor issue.

I just tested again on latest GB `master` & AMP `develop` and the AMP generated CSS looks different now:

```css
.is-style-circle-mask amp-img{
	-webkit-mask-image:url("data:image/svg+xml;utf8,<svgviewBox=\"00100100\"xmlns=\"http://www.w3.org/2000/svg\"><circlecx=\"50\"cy=\"50\"r=\"50\"/></svg>");
	mask-image:url("data:image/svg+xml;utf8,<svgviewBox=\"00100100\"xmlns=\"http://www.w3.org/2000/svg\"><circlecx=\"50\"cy=\"50\"r=\"50\"/></svg>");
	mask-mode:alpha;
	-webkit-mask-repeat:no-repeat;
	mask-repeat:no-repeat;
	-webkit-mask-size:contain;
	mask-size:contain;
	-webkit-mask-position:center;
	mask-position:center;
	border-radius:none;
}
```

`<svg viewBox` is still turned into `<svgviewBox` and the mask still doesn't work.

Now, when I just override AMP's mangled CSS with the one from Gutenberg, the result looks like this:

![Screenshot 2019-10-18 at 11 01 26](https://user-images.githubusercontent.com/841956/67081054-bd032880-f196-11e9-8127-72d2d0713e78.png)
