### ISSUE TITLE
Class selectors for .focus should be automatically converted into :focus-within pseudo class selectors

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#3585]
## Feature description

Many themes include JS logic to toggle a `focus` class on an element when focus is anywhere inside. For example:

* Twenty Seventeen: https://github.com/WordPress/wordpress-develop/blob/67a937a2fd93cc2227aa5472239365b4c7eaf803/src/wp-content/themes/twentyseventeen/assets/js/navigation.js#L68-L107
* Twenty Sixteen: https://github.com/WordPress/wordpress-develop/blob/67a937a2fd93cc2227aa5472239365b4c7eaf803/src/wp-content/themes/twentysixteen/js/functions.js#L73-L109
* Underscores: https://github.com/Automattic/_s/blob/28f0a5b4e56a5dc3cba94749a208eb478fe224d4/js/navigation.js#L48-L104

They then include CSS like Twenty Seventeen has here:

```css
.main-navigation ul ul li:hover > ul,
.main-navigation ul ul li.focus > ul {
	left: 100%;
	right: auto;
}
```

This causes a submenu to appear when focus is anywhere inside of the subtree.

The JS logic to toggle the `focus` class on elements is not feasible in AMP, so the AMP plugin uses a drop-in replacement by patching patching the core themes to use the `:focus-within` pseudo class in selectors that originally used `.focus`, for example:

https://github.com/ampproject/amp-wp/blob/884b805aa1b754383c44a7a909e859dd39427327/includes/sanitizers/class-amp-core-theme-sanitizer.php#L1065-L1073

This is not great because it means there are duplicated CSS rules, resulting in unoptimized CSS such as:

```css
.main-navigation ul ul li:hover > ul {
	left: 100%;
	right: auto;
	/* ... */
}
.main-navigation ul ul li:focus-within > ul {
	left: 100%;
	right: auto;
	/* ... */
}
```

Ideally these should be combined into one style rule because the properties are the same:

```css
.main-navigation ul ul li:hover > ul,
.main-navigation ul ul li:focus-within > ul {
	left: 100%;
	right: auto;
	/* ... */
}
```

Moreover, this is also not good because the process of making any theme AMP compatible would require copying `.focus`-selector style rules to `:focus-within`-selector style rules. (Note that `:focus-within` is supported by [80%+ of browsers](https://caniuse.com/#feat=css-focus-within).)

We can eliminate these painpoints by simply enhancing the CSS sanitizer to automatically replace `.focus` with `:focus-within` when processing a pared stylesheet. There is a natural place for this as well, inside of `\AMP_Style_Sanitizer::ampify_ruleset_selectors()`.

The class name(s) used should be configurable in an arg to the style sanitizer. For example:

```php
add_filter( 'amp_content_sanitizers', function( $sanitizers ) {
	$sanitizers['AMP_Style_Sanitizer']['focus_within_classes'] = [ 'enfocado' ];
	return $sanitizers;
} );
```

This would allow a theme to prevent this replacement behavior entirely by doing:

```php
add_filter( 'amp_content_sanitizers', function( $sanitizers ) {
	$sanitizers['AMP_Style_Sanitizer']['focus_within_classes'] = [];
	return $sanitizers;
} );
```

Alternatively, if a page initially has element(s) with the `focus` class, the replacement would ideally be skipped. But this would seem somewhat rare.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A theme that uses a CSS rule with a selector containing `.focus` should automatically get converted to `:focus-within`.

## Implementation brief

* See above and https://github.com/ampproject/amp-wp/pull/3586

## QA testing instructions

* Ensure that nav submenu items are accessible when just navigating by tabbing with the keyboard.

## Demo

* 

## Changelog entry

* Convert `.focus` class selectors to `:focus-within` pseudo-class selectors
