### ISSUE TITLE
Evaluate possible transformation of !important properties in at-rules

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4116]
## Feature description

In the p2 theme has a `style-print.css` which contains:

```css
@page {
	margin: 1cm !important;
}
```

This is raising an `CSS_SYNTAX_INVALID_IMPORTANT` validation error in the plugin and is getting sanitized as:

```css
@page{margin:1cm}
```

This is good because the property is still there and the rule is not removed, but the `!important` is dropped. Consider a `@page` rule occurring later in the document:

```css
@page { margin:0; }
```
In AMP, this would unexpectedly override the former one since the former rule's `!important` qualifier was stripped, and the `amp-custom` styles would be:

```css
@page { margin:1cm; }
@page { margin:0; }
```

The only way I can think of to resolve this is to split out `!important` properties from such at-rules and move them to the bottom of `amp-custom`, for example:

```css
@page { margin:0; }
@page { margin:1cm; }
```

This should result in the desired effect.

Nevertheless, this issue is likely very rare to cause problems. It's something that should be kept in mind.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*
