### ISSUE TITLE
Semicolon at end of declaration block in media query produces invalid CSS

### ISSUE THREAD

**Issue by pierlon** [ampproject/amp-wp#4197]
## Bug Description

While reviewing the [lakshmi-lite](https://wordpress.org/themes/lakshmi-lite/) theme (apart of work for #4060), multiple instances of the following error can be observed in the AMP Validator when viewing a post:

```
CSS syntax error in tag 'style amp-custom' - end of stylesheet encountered in prelude of a qualified rule. 
```

I've tracked one cause of the issue to this snippet of CSS in the theme's style.css ([line 3063](https://themes.trac.wordpress.org/browser/lakshmi-lite/1.1/style.css#L3063)):

```css
@media (max-width: 450px) {
    
	#sidebar.positionleft,
	#sidebar.positionright {
		padding: 0;
	};
}

/* 7. FOOTER
-------------------------------------------------------------------*/


#lsi-footer-sidebar-container {
    margin: 0 auto;
}
```

As seen above, there's a semicolon after the last declaration block in the media query, and outside of that media query is another declaration block. A similar scenario can be seen on [line 219](https://themes.trac.wordpress.org/browser/lakshmi-lite/1.1/style.css#L219).

When the stylesheet above is processed by `\AMP_Style_Sanitizer`, it produces the following malformed CSS:

```css
@media (max-width: 450px){;
}




#lsi-footer-sidebar-container{margin:0 auto}
```

The issue seems to be with the parsing of the stylesheet in `\AMP_Style_Sanitizer::parse_stylesheet()`. The lingering semicolon is not stripped by [PHP_CSS_Parser](https://github.com/sabberworm/PHP-CSS-Parser) and is then prepended to the next rule outside of the media query during the [splitting of the stylesheet](https://github.com/ampproject/amp-wp/blob/fcbfe7e662c71d410c71ec6bf0f1b029f6388f8a/includes/sanitizers/class-amp-style-sanitizer.php#L1778).

## Expected Behaviour

The lingering semicolon should be stripped and valid CSS should be outputted.

## Steps to reproduce

1. Install and activate the [Lakshmi Lite](https://wordpress.org/themes/lakshmi-lite/) theme
2. Go to the AMP version of the Hello World post 
3. Observe the errors reported by the AMP Validator. View the page source to see the malformed CSS.

## Screenshots

Malformed CSS produced from stylesheet of theme:

![image](https://user-images.githubusercontent.com/16200219/73417001-7cc35280-430e-11ea-9c68-07e7a147ec27.png)

## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*
