### ISSUE TITLE
Tree shaker removes CSS style rules for amp-date-picker classes

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#4334]
## Bug Description

As reported in the [support forum](https://wordpress.org/support/topic/amp-datepicker-unable-to-appy-custom-style-css/), styling the `amp-date-picker` component is difficult because style rules that target classes which the component adds via JS are removed by the tree-shaker. For example:

```css
amp-date-picker .CalendarMonth_caption {  
  background-image: linear-gradient(#b8b8b8, #5e5e5e);
  padding: 12px 0px;
}
amp-date-picker .amp-date-picker-calendar-container .CalendarMonth_caption {
  background-image: linear-gradient(#b8b8b8, #5e5e5e);
  padding: 12px 0px;
}
.amp-date-picker-calendar-container .CalendarMonth_caption {
  background-image: linear-gradient(#b8b8b8, #5e5e5e);
  padding: 12px 0px;	
}
```

A workaround is to ensure that all CSS selectors have an `amp-date-picker` ancestor prefix, and then to add this plugin code:

```php
// Temporary workaround for amp-date-picker class names having CSS selectors being tree-shaken.
add_filter( 'amp_content_sanitizers',
	function ( $sanitizers ) {
		$sanitizers['AMP_Style_Sanitizer']['dynamic_element_selectors'] = array_merge(
			! empty( $sanitizers['AMP_Style_Sanitizer']['dynamic_element_selectors'] ) ? $sanitizers['AMP_Style_Sanitizer']['dynamic_element_selectors'] : [],
			[
				// Modified from from protected AMP_Style_Sanitizer::$DEFAULT_ARGS.
				'amp-list',
				'amp-live-list',
				'[submit-error]',
				'[submit-success]',
				'amp-script',

				// New.
				'amp-date-picker',
			]
		);

		return $sanitizers;
	}
);
```

## Expected Behaviour

If an `amp-date-picker` is on the page, all of the class names that can be used in an `amp-date-picker` should be considered exempt from tree-shaking.

## Steps to reproduce

Create a Custom HTML block with the following contents:

```html
<style>
amp-date-picker .CalendarMonth_caption {  
  background-image: linear-gradient(#b8b8b8, #5e5e5e);
  padding: 12px 0px;
}
amp-date-picker .amp-date-picker-calendar-container .CalendarMonth_caption {
  background-image: linear-gradient(#b8b8b8, #5e5e5e);
  padding: 12px 0px;
}
.amp-date-picker-calendar-container .CalendarMonth_caption {
  background-image: linear-gradient(#b8b8b8, #5e5e5e);
  padding: 12px 0px;	
}
</style>
<amp-date-picker layout="fixed-height" height="360"></amp-date-picker>
```

View the AMP version of the page and notice that the date picker header does not have the expected gradient.

## Screenshots

Expected:

![image](https://user-images.githubusercontent.com/134745/75280572-cc3f6480-5861-11ea-9d0f-179f4f0b2575.png)

Actual:

![image](https://user-images.githubusercontent.com/134745/75280543-c184cf80-5861-11ea-9222-e7d631df4097.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*
